### ISSUE TITLE
tests for gauss_method.h

### ISSUE THREAD

**Issue by Ivan-Sergeyev** [Ivan-Sergeyev/slae_alg_comp#12]
add gauss_method_test.h and implement tests for [gauss_method.h](gauss_method.h)

the tests can be the same as for [jacobi_method.h](jacobi_method.h)

**Comment by IlyaFed** [comment]
I check answer of my method.

**Comment by Ivan-Sergeyev** [comment]
closed with 6e6202fd294e0be659dc6578289ea620fb782db4
